parameters:
    elasticsearch_hosts:
        - "localhost:9200"

services:
    elasticsearch.client:
        class: Elasticsearch\Client
        arguments:
            -
                hosts: "%elasticsearch_hosts%"
