parameters:
    elasticsearch_hosts:
        - "localhost:9200"
    elasticsearch_connectionParams:
        auth: []

services:
    elasticsearch.client:
        class: IC\ElasticsearchBundle\Client
        arguments:
            -
                hosts: "%elasticsearch_hosts%"
                connectionParams: "%elasticsearch_connectionParams%"
